### ISSUE TITLE
Regarding security notice

### ISSUE THREAD

**Issue by hmenke** [luakit/luakit.github.io#2]
The security notice in the download section is outdated or at least incomplete.  It states

> [...] Debian and OpenSUSE ship outdated and vulnerable versions in their stable channel

For Debian this is not (no longer?) true.  I guess the notice was referring to Debian 8 Jessie which indeed only provided `libwebkit2gtk-4.0-37` in version `2.6.2+dfsg1-4`.  The most recent stable branch, Debian 9 Stretch, on the other hand provides `2.16.6-0+deb9u1` (or even `2.18.4-1~bpo9+1` in `stretch-backports`).  I'm not familiar with the security update status of the various WebKit versions, but if any of the more recent versions suffice, you might want to consider adjusting the notice.

**Comment by aidanholm** [comment]
Thanks for pointing this out. Unfortunately version 2.16, although a vast improvement, is still vulnerable to various bugs that have been fixed in the 2.18 branch. The version in backports is up to date, however.

I'll look at updating the information on the page; unfortunately I don't have the time to update this info with every point release on the relevant platforms, so the information is always going to be a bit general.
